### PR TITLE
build: update to wlroots 0.17

### PR DESCRIPTION
**Pull request by ifreund**
Edit:

This branch seems to be nearly ready to merge.

I've hidden the comments I believe to be discussing outdated issues in order to make it easier to determine what is left to do before merging this branch. If I've made any errors there please let me know :)

### CODE REVIEW

**Comment by MaxVerevkin** [comment]
Popups break everything. To reproduce:
- Open firefox
- Right-click anywhere

Backtrace:

```
(gdb) bt full
#0  0x00007f430cfcb83c in  () at /usr/lib/libc.so.6
#1  0x00007f430cf7b668 in raise () at /usr/lib/libc.so.6
#2  0x00007f430cf634b8 in abort () at /usr/lib/libc.so.6
#3  0x00000000002a5269 in os.abort () at /usr/lib/zig/std/os.zig:601
#4  0x0000000000265cb4 in debug.panicImpl (trace=0x0, first_trace_addr=..., msg=...) at /usr/lib/zig/std/debug.zig:441
#5  0x0000000000264487 in builtin.default_panic (msg=..., error_return_trace=0x0, ret_addr=...) at /usr/lib/zig/std/builtin.zig:813
        first_trace_addr = 2979141
#6  0x00000000002d7545 in XdgPopup.handleReposition (listener=0x2b8ebf8) at XdgPopup.zig:89
        box = {x = 45673464, y = 0, width = 46723928, height = 0}
        root_lx = 46723928
        xdg_popup = 0x2b8ebb0
        output = 0x0
        root_ly = 0
#7  0x00000000002aebc4 in XdgPopup.create (wlr_xdg_popup=0x2c8f2a0, root=0x2cc2950, parent=0x2cc2950) at XdgPopup.zig:60
        xdg_popup = 0x2b8ebb0
#8  0x00000000002ae942 in XdgToplevel.handleNewPopup () at XdgToplevel.zig:272
        self = 0x30433b0
        listener = 0x3043448
        wlr_xdg_popup = 0x2c8f2a0
#9  wayland_server_core.Listener(*types.xdg_shell.XdgPopup).setNotify__struct_11691.wrapper (listener=0x3043448, data=0x2c8f2a0)
    at /home/maxv/river/zig-cache/o/ab99d28532c391e4061d54456ff1a4e4/wayland_server_core.zig:559
#10 0x00007f430d33e01e in wl_signal_emit_mutable () at /usr/lib/libwayland-server.so.0
#11 0x00007f430d19bbe3 in  () at /usr/lib/libwlroots.so.12
#12 0x00007f430ce004f6 in  () at /usr/lib/libffi.so.8
#13 0x00007f430cdfcf5e in  () at /usr/lib/libffi.so.8
#14 0x00007f430cdffb73 in ffi_call () at /usr/lib/libffi.so.8
#15 0x00007f430d33cada in  () at /usr/lib/libwayland-server.so.0
#16 0x00007f430d341180 in  () at /usr/lib/libwayland-server.so.0
#17 0x00007f430d33fae2 in wl_event_loop_dispatch () at /usr/lib/libwayland-server.so.0
#18 0x00007f430d3402d7 in wl_display_run () at /usr/lib/libwayland-server.so.0
#19 0x00000000002651a2 in main.main () at main.zig:132
        startup_command = {ptr = 0x23112e0 "p\251\312\002", len = 29}
        result = {args = {ptr = 0x7fff7ce7e630, len = 0}, flags = {c = {ptr = 0x0, len = 0}, log-level = {ptr = 0x7fff7ce7f955 "info", len = 4}, h = false, version = false}}
        child_pgid = {data = 88038, some = 1 '\001'}
```

River log:

```
debug(cursor): focused client set cursor
debug(layout): starting layout demand 'luatile' on output 'HDMI-A-1'
debug(layout): layout 'luatile' on output 'HDMI-A-1' pushed view dimensions: 0 0 1920 1056
debug(layout): layout 'luatile' on output 'HDMI-A-1' commited
debug(transaction): commiting transaction
thread 87991 panic: attempt to use null value
/home/maxv/river/river/XdgPopup.zig:89:72: 0x2d7544 in handleReposition (river)
    const output = switch (SceneNodeData.fromNode(&xdg_popup.root.node).?.data) {
                                                                       ^
/home/maxv/river/river/XdgPopup.zig:60:21: 0x2aebc3 in create (river)
    handleReposition(&xdg_popup.reposition);
                    ^
/home/maxv/river/river/XdgToplevel.zig:272:20: 0x2ae941 in wrapper (river)
    XdgPopup.create(wlr_xdg_popup, self.view.popup_tree, self.view.popup_tree) catch {
                   ^
???:?:?: 0x7f430d33e01d in ??? (libwayland-server.so.0)
Unwind information for `libwayland-server.so.0:0x7f430d33e01d` was not available, trace may be incomplete
```

**Comment by MaxVerevkin** [comment]
Here is a patch to fix popups:

```patch
diff --git a/river/SceneNodeData.zig b/river/SceneNodeData.zig
index 536a714..1c9bffd 100644
--- a/river/SceneNodeData.zig
+++ b/river/SceneNodeData.zig
@@ -51,12 +51,17 @@ pub fn attach(node: *wlr.SceneNode, data: Data) error{OutOfMemory}!void {
 }
 
 pub fn fromNode(node: *wlr.SceneNode) ?*SceneNodeData {
+    if (@as(?*SceneNodeData, @ptrFromInt(node.data))) |scene_node_data| {
+        return scene_node_data;
+    }
+
     var it: ?*wlr.SceneTree = node.parent;
     while (it) |tree| : (it = tree.node.parent) {
         if (@as(?*SceneNodeData, @ptrFromInt(tree.node.data))) |scene_node_data| {
             return scene_node_data;
         }
     }
+
     return null;
 }
 ```

**Comment by ifreund** [comment]
Starting gimp under xwayland crashes river for me. Otherwise I don't know of any remaining issues.

Thanks all for the testing and bug reports for this branch here and on IRC.

**Comment by ifreund** [comment]
Ah, it looks like the gamma-control protocol implementation is currently broken on this branch as well due to changes in wlroots: https://gitlab.freedesktop.org/wlroots/wlroots/-/merge_requests/4046

**Comment by praschke** [comment]
closing fcitx5 or xeyes in xwayland crashes river

backtrace:
```
(gdb) bt
#0  0x00007ffff7bc5d7c in __pthread_kill_implementation ()
   from /nix/store/qn3ggz5sf3hkjs2c797xf7nan3amdxmp-glibc-2.38-27/lib/libc.so.6
#1  0x00007ffff7b769c6 in raise () from /nix/store/qn3ggz5sf3hkjs2c797xf7nan3amdxmp-glibc-2.38-27/lib/libc.so.6
#2  0x00007ffff7b5f8fa in abort () from /nix/store/qn3ggz5sf3hkjs2c797xf7nan3amdxmp-glibc-2.38-27/lib/libc.so.6
#3  0x00000000002a5a39 in os.abort () at /nix/store/mgh01i003x4cm50d3k97jaa2ys935msg-zig-0.11.0/lib/std/os.zig:601
#4  0x0000000000266614 in debug.panicImpl (trace=0x0, first_trace_addr=..., msg=...)
    at /nix/store/mgh01i003x4cm50d3k97jaa2ys935msg-zig-0.11.0/lib/std/debug.zig:441
#5  0x0000000000264de7 in builtin.default_panic (msg=..., error_return_trace=0x0, ret_addr=...)
    at /nix/store/mgh01i003x4cm50d3k97jaa2ys935msg-zig-0.11.0/lib/std/builtin.zig:813
#6  0x00000000002b1685 in wayland_server_core.Listener(*xwayland.xwayland.XwaylandSurface).setNotify__struct_11870.wrapper (listener=0xd037c8, data=0x0)
    at /home/stel/work/z/river/river/zig-cache/o/36ac50c6aa44976f1e3fe1c36c598334/wayland_server_core.zig:559
#7  0x00007ffff7f3fa1c in wl_signal_emit_mutable ()
   from /nix/store/nrkv4q1gpi8qfvrj06ip5lg72rpqq3jb-wayland-1.22.0/lib/libwayland-server.so.0
#8  0x00007ffff7dcfb83 in xwayland_surface_destroy ()
   from /nix/store/c33wswj09f6pvmcrajd4j1v3339z88dd-wlroots-0.17.0/lib/libwlroots.so.12
#9  0x00007ffff7dd227a in x11_event_handler ()
   from /nix/store/c33wswj09f6pvmcrajd4j1v3339z88dd-wlroots-0.17.0/lib/libwlroots.so.12
#10 0x00007ffff7f418f2 in wl_event_loop_dispatch ()
   from /nix/store/nrkv4q1gpi8qfvrj06ip5lg72rpqq3jb-wayland-1.22.0/lib/libwayland-server.so.0
#11 0x00007ffff7f3f455 in wl_display_run ()
   from /nix/store/nrkv4q1gpi8qfvrj06ip5lg72rpqq3jb-wayland-1.22.0/lib/libwayland-server.so.0
#12 0x0000000000265b02 in main.main () at main.zig:132
```

log:
```
debug(view): view 'xeyes' unmapped
debug(layout): starting layout demand 'rivercarro' on output 'WL-1'
debug(layout): layout 'rivercarro' on output 'WL-1' pushed view dimensions: 6 6 1124 1006
debug(layout): layout 'rivercarro' on output 'WL-1' commited
debug(transaction): started transaction with 1 pending configure(s)
thread 543863 panic: cast causes pointer to be null
/home/stel/work/z/river/river/zig-cache/o/36ac50c6aa44976f1e3fe1c36c598334/wayland_server_core.zig:559:75: 0x2b1684 in wrapper (river)
                        @call(.always_inline, notify, .{ listener, @as(T, @ptrFromInt(@intFromPtr(data))) });
                                                                          ^
???:?:?: 0x7ffff7f3fa1b in ??? (libwayland-server.so.0)
Unwind information for `libwayland-server.so.0:0x7ffff7f3fa1b` was not available, trace may be incomplete
```

**Comment by novakne** [comment]
> Starting gimp under xwayland crashes river for me.

Spotify crash river for me too, for some reasons it seems that the `xwayland_surface`  arg in `Server.handleNewXwaylandSurface()` is null. It literally crash trying to print the log [here](https://github.com/riverwm/river/blob/master/river/Server.zig#L270-L272)
I know almost nothing about the xwayland part of river, so I have no idea how this is possible though

**Comment by ifreund** [comment]
Alright, the Xwayland crashes are now fixed as far as I know.

**Comment by MaxVerevkin** [comment]
I can reproduce #781 again on this branch. The log and back trace are almost identical.

<details>

Log

```
info(output_manager): applying output configuration
info(wlroots): [backend/drm/drm.c:782] connector eDP-1: Modesetting with 1920x1080 @ 60.056 Hz
debug(transaction): commiting transaction
thread 2194693 panic: reached unreachable code
/usr/lib/zig/std/debug.zig:343:14: 0x26f33c in assert (river)
    if (!ok) unreachable; // assertion failure
             ^
/home/maxv/river/river/Output.zig:533:28: 0x2bcc64 in wrapper (river)
        .unlocked => assert(server.lock_manager.state != .locked),
                           ^
```

Back trace

```
(gdb) bt full
#0  0x00007fecf07b383c in  () at /usr/lib/libc.so.6
#1  0x00007fecf0763668 in raise () at /usr/lib/libc.so.6
#2  0x00007fecf074b4b8 in abort () at /usr/lib/libc.so.6
#3  0x00000000002ae209 in os.abort () at /usr/lib/zig/std/os.zig:601
#4  0x000000000026ece4 in debug.panicImpl (trace=0x0, first_trace_addr=..., msg=...) at /usr/lib/zig/std/debug.zig:441
#5  0x000000000026d4b7 in builtin.default_panic (msg=..., error_return_trace=0x0, ret_addr=...) at /usr/lib/zig/std/builtin.zig:813
        first_trace_addr = 2552637
#6  0x000000000026f33d in debug.assert (ok=false) at /usr/lib/zig/std/debug.zig:343
#7  0x00000000002bcc65 in Output.handlePresent () at Output.zig:533
        output = 0x2d1d1e0
        listener = 0x2d1d3b8
        event = 0x7fffa298d9b0
#8  wayland_server_core.Listener(*types.output.Output.event.Present).setNotify__struct_12087.wrapper (listener=0x2d1d3b8, data=0x7fffa298d9b0)
    at /home/maxv/river/zig-cache/o/ab99d28532c391e4061d54456ff1a4e4/wayland_server_core.zig:559
#9  0x00007fecf0b2601e in wl_signal_emit_mutable () at /usr/lib/libwayland-server.so.0
#10 0x00007fecf096e9cb in wlr_output_send_present () at /usr/lib/libwlroots.so.12
#11 0x00007fecf09618bd in  () at /usr/lib/libwlroots.so.12
#12 0x00007fecf05d6907 in drmHandleEvent () at /usr/lib/libdrm.so.2
#13 0x00007fecf095f49e in  () at /usr/lib/libwlroots.so.12
#14 0x00007fecf0b27ae2 in wl_event_loop_dispatch () at /usr/lib/libwayland-server.so.0
#15 0x00007fecf0b282d7 in wl_display_run () at /usr/lib/libwayland-server.so.0
#16 0x000000000026e1d2 in main.main () at main.zig:132
        startup_command = {ptr = 0x238f2e0 "`8\027\003", len = 29}
        result = {args = {ptr = 0x7fffa298e790, len = 0}, flags = {c = {ptr = 0x0, len = 0}, log-level = {ptr = 0x7fffa298f9d0 "info", len = 4}, h = false, version = false}}
        child_pgid = {data = 2194739, some = 1 '\001'}
```

</details>

**Comment by ifreund** [comment]
> River crashes when `wp_viewport_set_source` is set out of bounds. The assertion failure comes from wlroots. For reference, master branch doesn't complain and renders with something that looks like `GL_CLAMP_TO_EDGE` and hyprland correctly sends `out_of_buffer` protocol error.

That one is an upstream wlroots issue that has been fixed already and will be included in 0.17.1: https://gitlab.freedesktop.org/wlroots/wlroots/-/issues/3766

**Comment by praschke** [comment]
i can no longer set custom modes with wlr-randr, river crashes with a segfault in handle_page_flip from wlroots.

**Comment by praschke** [comment]
custom mode breakage:
- rivercarro layout completely fails
- wbg goes black but restores image once the custom mode is removed
- firefox and yambar crash
- anki and foot do not crash
- wine cannot create windows with "Failed to read display config"
- a new foot can't be launched with "no monitors available"

**Comment by MaxVerevkin** [comment]
With two monitors, I cannot focus the second output. `focus-output next` and `send-to-output next` do nothing.

**Comment by ifreund** [comment]
RE the custom mode stuff, this is likely rooted in the now fixed wlroots bug: https://gitlab.freedesktop.org/wlroots/wlroots/-/merge_requests/4499

**Comment by ifreund** [comment]
wlroots 0.17.1 has been released and has fixes for several of the regressions reported here

**Comment by ifreund** [comment]
> I can reproduce #781 again on this branch. The log and back trace are almost identical.

This should be fixed now, as well as other major bugs related to the wlr-output-manangement implementation.

> I talked about it on irc but I'm asking about it here too in case, am I the only one with imperfect frames shown when closing a windows? i.e. the border is displayed without any app inside of it for one frame, happens with every app.

I can't reproduce this, does anyone else have this issue?

> With two monitors, I cannot focus the second output. `focus-output next` and `send-to-output next` do nothing.

I'm currently away from home and will need to get ahold of a second monitor to test this. I suspect it may have also been fixed by the most recent commit though. If so, @novakne's frame-perfection issue that I can't reproduce would be the only remaining issue blocking merge afaik.

**Comment by ifreund** [comment]
I'm going to hide the comments discussing bugs that I believe to be outdated to make it easier to see the remaining blockers. If anyone thinks I've hidden something that still needs a fix before merging this branch please let me know :)

**Comment by ifreund** [comment]
> i can no longer set custom modes with wlr-randr, river crashes with a segfault in handle_page_flip from wlroots.

I can actually still reproduce this when not specifiying the refresh rate with wlr-randr. If I set the refresh rate as well custom modes seem to work fine now with my latest commits and wlroots 0.17.1.

I will investigate the cause of this crash.

**Comment by ifreund** [comment]
The crash that occurs when omitting a refresh rate for a custom mode appears to be a wlroots bug, I've opened https://gitlab.freedesktop.org/wlroots/wlroots/-/issues/3791

**Comment by MaxVerevkin** [comment]
> With two monitors, I cannot focus the second output. focus-output next and send-to-output next do nothing.

Now it it's the opposite: I can focus disabled outputs. Also disabling an output does not transfer the views and focus to another output.

**Comment by ifreund** [comment]
> > With two monitors, I cannot focus the second output. focus-output next and send-to-output next do nothing.
> 
> Now it it's the opposite: I can focus disabled outputs. Also disabling an output does not transfer the views and focus to another output.

Thanks for testing! I'm pretty sure I see what happened, maybe I've gotten it right this time :)

**Comment by MaxVerevkin** [comment]
Something is wrong with output positions: I have two outputs with the same resolution, `wlr-randr` says they have different positions and do not overlap, but they both show the same image. Cursor input only works on laptop display. Disabling it leads to cursor input not working at all. Changing the position with `wlr-randr` doesn't work too.

**Comment by ifreund** [comment]
> Something is wrong with output positions: I have two outputs with the same resolution, `wlr-randr` says they have different positions and do not overlap, but they both show the same image. Cursor input only works on laptop display. Disabling it leads to cursor input not working at all. Changing the position with `wlr-randr` doesn't work too.

Thanks for testing, that should be fixed now as well. Third time's the charm :)

**Comment by MaxVerevkin** [comment]
Thanks, works now :) One last thing - cursor can focus disabled outputs with the cursor.

**Comment by ifreund** [comment]
> Thanks, works now :) One last thing - cursor can focus disabled outputs.

Of course it can, I forgot another detail. It should hopefully work now, I just force-pushed as there's no real reason to split that into a different commit.

**Comment by novakne** [comment]
> If so, @novakne's frame-perfection issue that I can't reproduce would be the only remaining issue blocking merge afaik.

Is there anything I can do to help with this? I have no idea what could cause this, is this something new in wlroots, river, my laptop starting to struggle with wlroots 0.17, I don't know where to search

**Comment by ifreund** [comment]
> Is there anything I can do to help with this? I have no idea what could cause this, is this something new in wlroots, river, my laptop starting to struggle with wlroots 0.17, I don't know where to search

Do you mean that river runs noticeably slower using wlroots 0.17 compared to 0.16? A debug log of river starting up would give information about the graphics drivers wlroots is using and might shed some light.

What kind of graphics hardware does your laptop have?

**Comment by ifreund** [comment]
I think it's time to land this. The only remaining regression reported with this branch has not yet been reproduced outside of @novakne's machine and pushing it to master may help get more bug reports from other users and aid debugging.

Furthermore, I'd like to finally land #859 which requires wlroots 0.17.1 for correct behavior in some cases.

Thanks everyone for the testing and bug reports here!

**Comment by novakne** [comment]
> Do you mean that river runs noticeably slower using wlroots 0.17 compared to 0.16?

Not really, the imperfect frame is the only thing I can see at least. It was more like about maybe a race condition or something that happens on computer less powerful like it happens for some bugs. Anyway with this pushed to master we'll see if I'm still the only one with this, and I'll try to look a bit more into it when I have the time.

**Comment by ifreund** [comment]
The frame imperfection bug on closing windows should be fixed by db70868c0458b51353677ed9a0028d1030da0f60.

Thanks tiosgz for reminding me that this kind of issue is very hard to notice if you only test with dark background terminal windows on a dark background of the same color :D

**Pull request merged**
