### PR TITLE
initial tablet support

### PR DESCRIPTION
**Pull request by MaxVerevkin**
Emulates pointer. Proper support is blocked by https://github.com/swaywm/zig-wlroots/pull/35. ~~Depends on https://github.com/swaywm/zig-wlroots/pull/57 and https://github.com/swaywm/zig-wlroots/pull/58.~~

### CODE REVIEW

**Comment by MaxVerevkin** [comment]
Relevant issue: #162

**Comment by salameme** [comment]
I am very interested in this feature, any way I can help?

**Comment by MaxVerevkin** [comment]
> I am very interested in this feature, any way I can help?

I think the next step is to resolve merge conflicts on #35 and port it to zig 0.10 (if needed).

**Comment by itshog** [comment]
Hello, I just wanted to say that I'm willing to help testing this feature!

**Comment by ifreund** [comment]
Superseded by 49a779b24d1a3a9999b33f52468f760153cc5d7f

If you want to work on adding pointer emulation support on top of the new tablet tool support feel free to open a PR. Note that I probably won't review it before 0.3.0 though.

**Pull request closed without merging**
