### PR TITLE
Cursor: implement initial touch support

### PR DESCRIPTION
**Pull request by ifreund**
Still TODO are:
- Touch support for drags
- Mapping input devices to outputs (necessary for good multi-monitor
touch support)

### CODE REVIEW

**Comment by ifreund** [comment]
Any testing of this PR would be much appreciated as I don't have any touch hardware to test this on myself.

**Comment by NickHastings** [comment]
> Any testing of this PR would be much appreciated as I don't have any touch hardware to test this on myself.

Just tested it. Worked great with firefox. Swipe scrolling, pinch zoom, and pressing links all worked.

Didn't find anything weird when using the mouse either.

Not sure what else to test but it looks good to me.

**Comment by ifreund** [comment]
Alright, I've had a look at implementing touch grabs but it's kinda hairy and the wlroots API here doesn't seem to be the greatest. I think I'll just merge this and open a issues for those additional features.

**Comment by ifreund** [comment]
> I think I'll just merge this and open a issues for those additional features.

#634, #635

**Pull request merged**
