### PR TITLE
Add installation section

### PR DESCRIPTION
**Pull request by Drsheppard01**

### CODE REVIEW

**Comment by wiki-me** [comment]
Repology has a widget that shows in what distro's a certain software is available (see the cataclysm dda [readme](https://github.com/CleverRaven/Cataclysm-DDA/blob/master/README.md) for an example).

That could be a more concise and easily maintainable alternative.

**Comment by Drsheppard01** [comment]
firstly, Repology does not hide Fedora Copr, and also I find river in Gentoo, which is not on repology

There are examples where both repology and software installation are used: 

https://github.com/peltoche/lsd
https://github.com/johnfactotum/foliate

**Comment by wiki-me** [comment]
Are you sure it's on gentoo?, i don't see it on the gentoo search page ([here](https://packages.gentoo.org/packages/search?q=river)), looks like some kind of bug in the gentoo website.

**Comment by Leon-Plickat** [comment]
We already have a repology badge in the readme.

---

I don't really think I get the point of this PR. All sane package managers have a search functionality, so we do not really need to list all available packages. Listing the exact commands is also weird to me: We should not need to explain people how to use the package managers of their distributions.

**Comment by Drsheppard01** [comment]
I wanted to show other installation options that are not affected by repology (Fedora COPR, Gentoo)

**Pull request closed without merging**
