### PR TITLE
ext-session-lock: implement protocol

### PR DESCRIPTION
**Pull request by ifreund**
- [x] Protocol merged to wayland-protocols https://gitlab.freedesktop.org/wayland/wayland-protocols/-/merge_requests/131
- [x] wlroots implementation merged https://gitlab.freedesktop.org/wlroots/wlroots/-/merge_requests/3414
- [x] wayland-protocols release
- [x] wlroots release

Since river tracks the latest wlroots releases, I've cherry-picked the wlroots commit linked above onto the 0.15.0 tag for testing. Branch here: https://gitlab.freedesktop.org/ifreund/wlroots/-/tree/session-lock-0.15

This can be tested with the swaylock implementation of this protocol here: https://github.com/swaywm/swaylock/pull/219

### CODE REVIEW

**Comment by ifreund** [comment]
The wlroots PR has been merged, now we're just waiting on wlroots `0.16`.

**Comment by ifreund** [comment]
waylock has now been rewritten and uses `ext-session-lock-v1`: https://github.com/ifreund/waylock

**Comment by gbrlsnchs** [comment]
Hey, I don't want to go too off-topic here, just wanna say _thanks_! Amazing work!

**Comment by ifreund** [comment]
Any users of this branch should be aware of this upstream libwayland bug that is particularly problematic for `ext-session-lock-v1` clients: https://gitlab.freedesktop.org/wayland/wayland/-/merge_requests/262

I've opened an MR to fix it in libwayland, but it may take a while until it's included in a release.

**Pull request merged**
